<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matt Bartok">
<meta name="author" content="Maroun Mezher">
<meta name="author" content="Tural Sadigov">
<meta name="dcterms.date" content="2022-12-08">

<title>MATH 254 - Did Flights Become Safer After 9/11?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Bartok_Mezher_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Bartok_Mezher_Project_files/libs/quarto-html/quarto.js"></script>
<script src="Bartok_Mezher_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Bartok_Mezher_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Bartok_Mezher_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Bartok_Mezher_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Bartok_Mezher_Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="Bartok_Mezher_Project_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="Bartok_Mezher_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Bartok_Mezher_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Bartok_Mezher_Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="Bartok_Mezher_Project_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<style>
    .quarto-title-block .quarto-title-banner {
      background: darkblue;
    }
    </style>

<script src="Bartok_Mezher_Project_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Bartok_Mezher_Project_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">MATH 254 - Did Flights Become Safer After 9/11?</h1>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-heading">Affiliations</div>
    
      <div class="quarto-title-meta-contents">
      Matt Bartok 
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Hamilton College
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      Maroun Mezher 
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Hamilton College
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      Tural Sadigov 
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Hamilton College
            </p>
        </div>
      </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 8, 2022</p>
      </div>
    </div>
      
    </div>
    
  <div>
    <div class="abstract">
      <div class="abstract-title">Abstract</div>
      In this paper we investigate whether airplanes themselves have become safer following the 9/11 terrorist attacks, as well as whether there is a difference in the safety of flights for airlines based inside versus outside the United States. We first regress fatal accidents on flight incidents for all airlines in an OLS simple linear regression, both before and after the 9/11 attacks. We then conduct a permutation test and another OLS regression (with an interaction term to distinguish between American and non-American based airlines) to determine if airlines based in the United States are safer or less safe than those based outside of the country. After running all of our models, we find that flights did indeed become safer following 9/11, and that flights on American airlines that experienced an incident are actually less safe than for flights on airlines not based in the United States.
    </div>
  </div>
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#background-and-significance" id="toc-background-and-significance" class="nav-link active" data-scroll-target="#background-and-significance"><span class="toc-section-number">1</span>  Background and Significance</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="toc-section-number">2</span>  Methods</a>
  <ul class="collapse">
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection"><span class="toc-section-number">2.1</span>  Data Collection</a></li>
  <li><a href="#variable-creation" id="toc-variable-creation" class="nav-link" data-scroll-target="#variable-creation"><span class="toc-section-number">2.2</span>  Variable Creation</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="toc-section-number">2.3</span>  Methodology</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="toc-section-number">3</span>  Results</a>
  <ul class="collapse">
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="toc-section-number">3.1</span>  Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#have-flight-incidents-become-deadlier-post-2000" id="toc-have-flight-incidents-become-deadlier-post-2000" class="nav-link" data-scroll-target="#have-flight-incidents-become-deadlier-post-2000"><span class="toc-section-number">3.1.1</span>  Have Flight Incidents Become Deadlier Post 2000?</a></li>
  <li><a href="#difference-in-fatal-accidents-between-american-and-non-american-airlines" id="toc-difference-in-fatal-accidents-between-american-and-non-american-airlines" class="nav-link" data-scroll-target="#difference-in-fatal-accidents-between-american-and-non-american-airlines"><span class="toc-section-number">3.1.2</span>  Difference in Fatal Accidents between American and Non-American Airlines</a></li>
  <li><a href="#how-much-is-the-difference-of-fatal-accidents-between-american-and-non-american-airlines" id="toc-how-much-is-the-difference-of-fatal-accidents-between-american-and-non-american-airlines" class="nav-link" data-scroll-target="#how-much-is-the-difference-of-fatal-accidents-between-american-and-non-american-airlines"><span class="toc-section-number">3.1.3</span>  How Much is The Difference of Fatal Accidents between American and Non-American Airlines?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussionconclusions" id="toc-discussionconclusions" class="nav-link" data-scroll-target="#discussionconclusions"><span class="toc-section-number">4</span>  Discussion/Conclusions</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="toc-section-number">4.1</span>  Limitations</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="toc-section-number">5</span>  References</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="toc-section-number">6</span>  Appendix</a>
  <ul class="collapse">
  <li><a href="#code-used" id="toc-code-used" class="nav-link" data-scroll-target="#code-used"><span class="toc-section-number">6.0.1</span>  Code used</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-1_99509ec33224dcd08fe59575eaab3a69">

</div>
<section id="background-and-significance" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Background and Significance</h1>
<p>When considering the most monumental disasters in human history, the terrorist attacks on September 11, 2001 (referred to as 9/11) often come to mind. Of the many takeaways society gathered from the horrific event, the most prominent may well have been the necessity to increase airline security to improve safety for those on board aircraft. While the implementation of the Transportation Security Administration (TSA) may invade one's privacy, it has indeed improved overall safety by decreasing the number of terrorist attacks on aircraft (Hunter). However, have aircraft themselves actually become safer?</p>
<p>The short answer to the question presented above is yes, largely due to the continuous technological advancements that influence aircrafts. In the past (namely throughout the twentieth century), the advancements in the aerospace industry have been nearly exclusively through better, typically lighter materials. However, new products used are not purely performance driven because there is this new idea of customer value, where companies decrease costs to maximize profit (Starke). This begs the question: are airlines cutting costs to increase profits to the extent where safety is being hindered? In other words, are aircrafts as safe as possible given the current level of technology? This is harder to answer than the former question presented, and is a driving force for our study.</p>
<p>The goal of our study is to improve the understanding of how safe aircrafts truly are, and if they have become more safe following the 9/11 attacks. We determine if, following 9/11, instances where aircrafts experienced incidents resulted in fewer fatalities on average than in the past. We define a flight incident as a scenario where an aircraft experiences a malfunction, which can range from a radio malfunction to a burst engine or a hijacking. Understanding the extent to which the safety of traveling via aircraft has truly improved will enable us to realize whether or not the aerospace field is lagging in terms of overall safety. Moreover, we are interested in whether there is a significant difference in the safety of flights for US based airlines versus non-US based airlines. We hypothesize that flights have increased in overall safety, where flights post 9/11 have a statistically significantly lower average rate of fatalities per incident than those prior to 9/11. Additionally, we hypothesize that American-based airlines are safer than non-American based airlines.</p>
</section>
<section id="methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methods</h1>
<section id="data-collection" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-collection"><span class="header-section-number">2.1</span> Data Collection</h2>
<p>The data for this project was collected from the Five Thirty Eight database on Github. The data, sourced from the Aviation Safety Network, accumulates data on flight incidents for all major commercial airlines, over a 30 year period. The 30 year period splits the data in half (1985-1999 and 2000-2014). The variables that the data collects are the number of available seat kilometers available every week, the number of incidents, the number of fatal incidents and the number of fatalities for each 15 year period. Each observation represents a major airline. The airlines marked by an asterisk mean that the observations include regional subsidiaries of the airline.</p>
</section>
<section id="variable-creation" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variable-creation"><span class="header-section-number">2.2</span> Variable Creation</h2>
<p>The data comes with eight original variables detailed in table 1 below. We created a Boolean variable to indicate whether an airline is American or not, as this variable helps us with our analysis. We also merged some variables into new ones in order to run some tests on them, such as total fatalities by airline which aggregates the total number of fatalities by airline from 1985 till 2014.</p>
<table class="table">
<caption>Variables in our data.</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>airline</code></td>
<td>Airline (asterisk indicates that regional subsidiaries are included)</td>
</tr>
<tr class="even">
<td><code>avail_seat_km_per_week</code></td>
<td>Available seat kilometers flown every week</td>
</tr>
<tr class="odd">
<td><code>incidents_85_99</code></td>
<td>Total number of incidents, 1985–1999</td>
</tr>
<tr class="even">
<td><code>fatal_accidents_85_99</code></td>
<td>Total number of fatal accidents, 1985–1999</td>
</tr>
<tr class="odd">
<td><code>fatalities_85_99</code></td>
<td>Total number of fatalities, 1985–1999</td>
</tr>
<tr class="even">
<td><code>incidents_00_14</code></td>
<td>Total number of incidents, 2000–2014</td>
</tr>
<tr class="odd">
<td><code>fatal_accidents_00_14</code></td>
<td>Total number of fatal accidents, 2000–2014</td>
</tr>
<tr class="even">
<td><code>fatalities_00_14</code></td>
<td>Total number of fatalities, 2000–2014</td>
</tr>
<tr class="odd">
<td><code>americanairline</code></td>
<td>Boolean variable. 1 indicates an American airline.</td>
</tr>
</tbody>
</table>
</section>
<section id="methodology" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="methodology"><span class="header-section-number">2.3</span> Methodology</h2>
<p>To determine if flights following 9/11 became safer, we first conduct two ordinary least squares (OLS) simple linear regressions. In the first regression, we regress the number of fatal accidents on the number of flight incidents for the data before the year 2000. The next regression is very similar to the first other than restricting the data for after the year 2000, where we again regress the number of fatal accidents on the number of incidents. We then compare our coefficients from the two regressions to see if flights following 2000 did truly become less deadly following the 9/11 attacks. It is important to note, as is discussed in a later section regarding limitations, that we are using the year 2000 instead of 2001 as the intervention year due to how our data is structured. Following our two initial OLS regressions, we run a permutation test to compare the overall safety of American based versus non-American based airlines. We compare the mean fatal accidents per airline on American and non-American airlines and determine if our results are statistically significant. Finally, we run a third OLS simple linear regression to show the effect of total incidents on total fatal accidents for American airlines. We do this by adding an interaction term - where we interact the variable for American airlines with the total number of incidents. This provides further analysis to compare the safety of American based airlines and non-American based airlines.</p>
</section>
</section>
<section id="results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results</h1>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-2_1b8879b989c64fb17709f156195208f9">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Summary Statistics</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> Sd </th>
   <th style="text-align:left;"> Min </th>
   <th style="text-align:left;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Number of Incidents (1985-1999) </td>
   <td style="text-align:left;"> 7.18 </td>
   <td style="text-align:left;"> 11.04 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 76 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fatal Accidents (1985-1999) </td>
   <td style="text-align:left;"> 2.18 </td>
   <td style="text-align:left;"> 2.86 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fatalities (1985-1999) </td>
   <td style="text-align:left;"> 112.41 </td>
   <td style="text-align:left;"> 146.69 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 535 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Number of Incidents (2000-2014) </td>
   <td style="text-align:left;"> 4.12 </td>
   <td style="text-align:left;"> 4.54 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fatal Accidents (2000-2014) </td>
   <td style="text-align:left;"> 0.66 </td>
   <td style="text-align:left;"> 0.86 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fatalities (2000-2014) </td>
   <td style="text-align:left;"> 55.52 </td>
   <td style="text-align:left;"> 111.33 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 537 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> American Airliners </td>
   <td style="text-align:left;"> 0.12 </td>
   <td style="text-align:left;"> 0.33 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 1 </td>
  </tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> N = 56 | Source: FiveThirtyEight</td>
</tr>
</tfoot>
</table>

</div>
</div>
<section id="hypothesis-testing" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="hypothesis-testing"><span class="header-section-number">3.1</span> Hypothesis Testing</h2>
<p>Our analysis includes three tests for different hypotheses that we include in our data. The tests, detailed below, help us understand patterns in terms of incidents and fatalities for all airlines, specifically American airlines, before and after the year 2000. In our tests, we use an alpha of 0.00625 for our significance level. We divide our initial alpha, 0.05, by 8 (0.00625) our number of hypothesis tests) to obtain the new significance level (in order to prevent p-hacking in our study.</p>
<ul>
<li>Two regressions where we regress the number number of fatal accidents on the number of flight incidents before 2000 (first regression) and after 2000 (second regression). We will then compare the coefficients between the two to determine whether flight incidents became more deadly post 2000 or not.</li>
<li>A permutation test to see whether the mean of fatal accidents between American and non-American airlines is statistically the same or not.</li>
<li>A regression showing the effect of total fatal accidents on the total number of incidents for American airlines.</li>
</ul>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-3_76817d0969a3f9cbe83068f9fb6b3a1a">

</div>
<section id="have-flight-incidents-become-deadlier-post-2000" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="have-flight-incidents-become-deadlier-post-2000"><span class="header-section-number">3.1.1</span> Have Flight Incidents Become Deadlier Post 2000?</h3>
<p>We are interested in looking at whether flight incidents weer more deadly in the 15 years period before or after 2000. In order to do that, we will be running two regressions with the number of incidents as the explanatory variable and the number of fatal accidents as the response variable.</p>
<section id="pre-2000" class="level4" data-number="3.1.1.1">
<h4 data-number="3.1.1.1" class="anchored" data-anchor-id="pre-2000"><span class="header-section-number">3.1.1.1</span> Pre 2000</h4>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-4_dfa961a54f96d0dfeef0c820751ffe05">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term            estimate std.error statistic  p.value
  &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)        0.584    0.238       2.45 1.74e- 2
2 incidents_85_99    0.222    0.0182     12.2  3.55e-17</code></pre>
</div>
</div>
<p>As we can see in the results above, being in an incident in the (1985-1999) range is associated with a 0.222 increase in fatal accidents (for every 1000 incidents, 222 of them will be fatal). The 0.222 coefficient is statistically significant.</p>
</section>
<section id="post-2000" class="level4" data-number="3.1.1.2">
<h4 data-number="3.1.1.2" class="anchored" data-anchor-id="post-2000"><span class="header-section-number">3.1.1.2</span> Post 2000</h4>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-5_3f3817b11ec289618bb8541831b37b7c">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term            estimate std.error statistic    p.value
  &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 (Intercept)        0.195    0.126       1.55 0.128     
2 incidents_00_14    0.113    0.0206      5.48 0.00000113</code></pre>
</div>
</div>
<p>The results in this section show that being in an incident in the range (2000-2014) is associated with an increase of 0.113 fatal accidents, with the coefficient being statistically significant (for every 1000 incidents, 113 of them will be fatal).</p>
<p>We can conclude that incidents have become less fatal after 2000 by a factor of 0.109 fatal accidents/incident.</p>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-6_b9704852a9e04cb6d470312703652281">
<div class="cell-output-display">
<p><img src="Bartok_Mezher_Project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="difference-in-fatal-accidents-between-american-and-non-american-airlines" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="difference-in-fatal-accidents-between-american-and-non-american-airlines"><span class="header-section-number">3.1.2</span> Difference in Fatal Accidents between American and Non-American Airlines</h3>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-7_ca3125888027d96fb7c7861f9b5bd053">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1   0.014</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Bartok_Mezher_Project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This test is a permutation test that looks for a significance in the difference in means between American and non-American airlines. What this means is that we are assuming that American and non-American airlines have the same average fatal accidents per airline. We then test this hypothesis using the data that we have through a permutation test.</p>
<p>Looking at the graph above, and knowing that the p-value is 0.014, we know that we do not have statistical significance. Thus, we can not reject the null hypothesis that the mean of fatal accidents for American and non-American airlines are the same.</p>
</section>
<section id="how-much-is-the-difference-of-fatal-accidents-between-american-and-non-american-airlines" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="how-much-is-the-difference-of-fatal-accidents-between-american-and-non-american-airlines"><span class="header-section-number">3.1.3</span> How Much is The Difference of Fatal Accidents between American and Non-American Airlines?</h3>
<p>In order to calculate this difference, we will be running a regression with the Total Number of Fatal Accidents as the response variable, the Total Number of Incidents as the key explanatory variable and an interaction term between the Total Number of Incidents and the American Airline variable. The coefficient on the interaction term should tell us the percentage points difference in fatal accident between American and non-American airlines.</p>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-8_0cd4bc32f9c2a786b470f8f25d4e5ade">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                             estimate std.error statistic  p.value
  &lt;chr&gt;                               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                         0.549    0.265       2.07 4.33e- 2
2 total_incidents                     0.193    0.0173     11.1  2.33e-15
3 americanairline1                   -1.92     1.01       -1.89 6.37e- 2
4 total_incidents:americanairline1    0.118    0.0383      3.08 3.30e- 3</code></pre>
</div>
</div>
<p>Based on the results from our test above, an American airline who had an incident is associated with a 0.118 fatal accidents increase compared to a non-American airline. Moreover, this coefficient is statistically significant.</p>
</section>
</section>
</section>
<section id="discussionconclusions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Discussion/Conclusions</h1>
<p>When we started looking at the data, we expected that we should see an improvement in airline safety post 2000. This was true indeed, as our first test showed that following the year 2000, airline incidents have indeed become less fatal. Moreover, we expected to see a discrepancy in rates of fatal accidents between American and non-American airlines which we did not see. However, we were surprised when we found that on average, American incidents have been historically more fatal than non-American incidents. This might be due to some artifacts in our data. This is because the fatalities from 9/11 are included in the data in a way that’s almost impossible to isolate, which means that with the data we have, we cannot tell whether US airlines these days are less (or more) fatal than other airlines.</p>
<p>Thus, in conclusion, we can conclude that flying has become less fatal following the turn of the century in general, with American airlines seeming to be lacking behind their non-American counterparts.</p>
<section id="limitations" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="limitations"><span class="header-section-number">4.1</span> Limitations</h2>
<p>There are two main issues relating to the limitations of our study. The first, as often is the case, is the small sample size (only 56 observations) of our data. Additionally, our data is structured in such a way that we cannot use the date September 11, 2001 as our intervention date to compare the safety of flights for before and after 9/11. The data is grouped into dates before 2000 and after 2000, so we use the turn of the 21st century as our intervention date instead of the actual date for 9/11. Thus, when we compare flights from "before and after 9/11", we really are comparing flights from before and after the year 2000.</p>
</section>
</section>
<section id="references" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> References</h1>
<p>[1] R Core Team (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.</p>
<p>[2] H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.</p>
<p>[3] Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686, https://doi.org/10.21105/joss.01686</p>
<p>[4] RStudio Team (2022). RStudio: Integrated Development Environment for R. RStudio, PBC, Boston, MA URL http://www.rstudio.com/.</p>
<p>[5] http://fivethirtyeight.com/features/should-travelers-avoid-flying-airlines-that-have-had-crashes-in-the-past/</p>
<p>[6] Hunter, J.A., Lambert, J.R. “Do we feel safer today? The impact of smiling customer service on airline safety perception post 9–11.” J Transp Secur 9, 35–56 (2016).</p>
<p>[7] Starke, Edgar A, Williams, James C. “Progress in Structural Materials for Aerospace Systems.” Acta Materialia, Pergamon, 14 Oct.&nbsp;2003.</p>
<p>[8] Quarto</p>
<p>[9] USCLAP template</p>
<p>[10] Nick Huntington-Klein (2022). vtable: Variable Table for Variable Documentation. R package version 1.3.4. https://CRAN.R-project.org/package=vtable</p>
</section>
<section id="appendix" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Appendix</h1>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-9_4dd03c51687ccb14148e121260bdb713">
<div class="cell-output-display">
<p><img src="Bartok_Mezher_Project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="code-used" class="level3" data-number="6.0.1">
<h3 data-number="6.0.1" class="anchored" data-anchor-id="code-used"><span class="header-section-number">6.0.1</span> Code used</h3>
<div class="cell" data-hash="Bartok_Mezher_Project_cache/html/unnamed-chunk-10_feb2a1c0aacc2e2f3775aa7dd7e0d9d6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Setting up the data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vtable)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>remote <span class="ot">&lt;-</span> <span class="st">'https://raw.githubusercontent.com/'</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>account <span class="ot">&lt;-</span> <span class="st">'fivethirtyeight/'</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>folder <span class="ot">&lt;-</span> <span class="st">'data/master/airline-safety/'</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>file <span class="ot">&lt;-</span> <span class="st">'airline-safety.csv'</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="fu">str_c</span>(remote, account, folder, file)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>flights</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co">#data wrangling and sumstats</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>american <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Alaska Airlines*"</span>, </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>              <span class="st">"American*"</span>, </span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Delta / Northwest*"</span>, </span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Hawaiian Airlines"</span>, </span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Southwest Airlines"</span>, </span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>              <span class="st">"United / Continental*"</span>, </span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>              <span class="st">"US Airways / America West*"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> </span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  flights <span class="sc">%&gt;%</span> </span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">americanairline =</span> <span class="fu">ifelse</span>(airline <span class="sc">%in%</span> american, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>avail_seat_km_per_week)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>labs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Number of Incidents (1985-1999)"</span>, </span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Fatal Accidents (1985-1999)"</span>, </span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Fatalities (1985-1999)"</span>, </span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Number of Incidents (2000-2014)"</span>, </span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Fatal Accidents (2000-2014)"</span>, </span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Fatalities (2000-2014)"</span> , </span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>          <span class="st">"American Airliners"</span>)</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>vtable<span class="sc">::</span><span class="fu">sumtable</span>(df, <span class="at">digits =</span> <span class="dv">2</span> , </span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"Summary Statistics"</span>, </span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>                 <span class="at">note =</span> <span class="st">"N = 56 | Source: FiveThirtyEight"</span>, </span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>                 <span class="at">labels =</span> labs, </span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>                 <span class="at">summ =</span> <span class="fu">c</span>(<span class="st">"mean(x)"</span>, <span class="st">"sd(x)"</span>, <span class="st">"min(x)"</span>, <span class="st">"max(x)"</span>), </span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fit.page =</span> <span class="dv">30</span>)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_fatal_accidents =</span> fatal_accidents_00_14 <span class="sc">+</span> fatal_accidents_85_99) <span class="sc">%&gt;%</span> </span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_incidents =</span> incidents_85_99 <span class="sc">+</span> incidents_00_14)</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a><span class="co">#hypothesis testing</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">'lm'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">'regression'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(fatal_accidents_85_99 <span class="sc">~</span> incidents_85_99, <span class="at">data =</span> df)</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model1)</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">'lm'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">'regression'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(fatal_accidents_00_14 <span class="sc">~</span> incidents_00_14, <span class="at">data =</span> df)</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model2)</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a><span class="co">#plot with model 1 and 2</span></span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> total_incidents, <span class="at">y =</span>total_fatal_accidents)) <span class="sc">+</span></span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="fl">0.222</span>, <span class="at">intercept =</span> <span class="fl">0.584</span>, <span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span> </span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="fl">0.113</span>, <span class="at">intercept =</span> <span class="fl">0.195</span>, <span class="at">color =</span> <span class="st">'blue'</span>) <span class="sc">+</span> </span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Incidents"</span>) <span class="sc">+</span> </span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Fatal Accidents"</span>) <span class="sc">+</span> </span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Relationship between total flight incidents and total fatal accidents"</span>) <span class="sc">+</span></span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>)) <span class="sc">+</span></span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">caption =</span> <span class="st">"Red Line: Pre 2000 | Blue Line: Post 2000"</span>)</span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a><span class="co">#permutation test</span></span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1776</span>)</span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>americanairline <span class="ot">&lt;-</span></span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.character</span>(df<span class="sc">$</span>americanairline)</span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a>obs_stat <span class="ot">&lt;-</span> </span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(total_fatal_accidents <span class="sc">~</span> americanairline) <span class="sc">%&gt;%</span> </span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">'diff in means'</span>, </span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a>            <span class="at">order =</span> <span class="fu">c</span>(<span class="st">'1'</span>, <span class="st">'0'</span>))</span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a>perm_dist <span class="ot">&lt;-</span> </span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(total_fatal_accidents <span class="sc">~</span> americanairline) <span class="sc">%&gt;%</span> </span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">'independence'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">'permute'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">'diff in means'</span>,</span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a>            <span class="at">order =</span> <span class="fu">c</span>(<span class="st">'1'</span>, <span class="st">'0'</span>))</span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-97"><a href="#cb5-97" aria-hidden="true" tabindex="-1"></a>perm_dist <span class="sc">%&gt;%</span> </span>
<span id="cb5-98"><a href="#cb5-98" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_p_value</span>(<span class="at">obs_stat =</span> obs_stat, <span class="at">direction =</span> <span class="st">'right'</span>)</span>
<span id="cb5-99"><a href="#cb5-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-100"><a href="#cb5-100" aria-hidden="true" tabindex="-1"></a>perm_dist <span class="sc">%&gt;%</span> </span>
<span id="cb5-101"><a href="#cb5-101" aria-hidden="true" tabindex="-1"></a>  <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb5-102"><a href="#cb5-102" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> obs_stat, <span class="at">direction =</span> <span class="st">'right'</span>)</span>
<span id="cb5-103"><a href="#cb5-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-104"><a href="#cb5-104" aria-hidden="true" tabindex="-1"></a><span class="co">#more hypothesis testing</span></span>
<span id="cb5-105"><a href="#cb5-105" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span></span>
<span id="cb5-106"><a href="#cb5-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-107"><a href="#cb5-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">'lm'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-108"><a href="#cb5-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">'regression'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-109"><a href="#cb5-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(total_fatal_accidents <span class="sc">~</span> total_incidents <span class="sc">*</span> americanairline, <span class="at">data =</span> df)</span>
<span id="cb5-110"><a href="#cb5-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-111"><a href="#cb5-111" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model3)</span>
<span id="cb5-112"><a href="#cb5-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-113"><a href="#cb5-113" aria-hidden="true" tabindex="-1"></a><span class="co">#appendix graph</span></span>
<span id="cb5-114"><a href="#cb5-114" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb5-115"><a href="#cb5-115" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(total_fatal_accidents, airline, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-116"><a href="#cb5-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">airlines =</span> <span class="fu">reorder</span>(airline, total_fatal_accidents))  </span>
<span id="cb5-117"><a href="#cb5-117" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-118"><a href="#cb5-118" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&gt;%</span> </span>
<span id="cb5-119"><a href="#cb5-119" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> total_fatal_accidents, <span class="at">y =</span> airlines)) <span class="sc">+</span></span>
<span id="cb5-120"><a href="#cb5-120" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb5-121"><a href="#cb5-121" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Airline"</span>) <span class="sc">+</span> </span>
<span id="cb5-122"><a href="#cb5-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Fatalities"</span>) <span class="sc">+</span> </span>
<span id="cb5-123"><a href="#cb5-123" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Total Fatal Accidents between 1985 and 2014"</span>) <span class="sc">+</span></span>
<span id="cb5-124"><a href="#cb5-124" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>, <span class="at">vjust =</span> <span class="dv">1</span>, <span class="at">hjust=</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">6</span>)) <span class="sc">+</span></span>
<span id="cb5-125"><a href="#cb5-125" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>