<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amrit Singh Aggarwal">
<meta name="author" content="Dean Atassi">
<meta name="author" content="Tural Sadigov">
<meta name="dcterms.date" content="2022-11-16">

<title>Investigating Racial Discrimination in HOLC Ratings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/clipboard/clipboard.min.js"></script>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/quarto-html/quarto.js"></script>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/quarto-html/popper.min.js"></script>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/quarto-html/anchor.min.js"></script>
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<style>
    .quarto-title-block .quarto-title-banner {
      background: darkturquoise;
    }
    </style>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/typedarray-0.1/typedarray.min.js"></script>
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/jquery-3.5.1/jquery.min.js"></script>
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="MATH 254 Project - Amrit _ Dean Final_files/libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="MATH 254 Project - Amrit _ Dean Final_files/libs/plotly-main-2.5.1/plotly-latest.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Investigating Racial Discrimination in HOLC Ratings</h1>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      Amrit Singh Aggarwal 
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Hamilton College
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      Dean Atassi 
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Hamilton College
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      Tural Sadigov 
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Hamilton College
            </p>
        </div>
      </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 16, 2022</p>
      </div>
    </div>
      
    </div>
    
  <div>
    <div class="abstract">
      <div class="abstract-title">Abstract</div>
      In this investigation we try to determine whether there is a relationship between HOLC grade and race, specifically whether they are independnet or not. We run several simple and multivarite regressions and conduct both simulated and traditional chi-squared tests for independence to get to our answer. We find that associations between whether a county has a black plural population and their HOLC rating assignment to not be independent. This result suggests that their is some potential racial discrimination regarding HOLC grading.
    </div>
  </div>
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#background-and-significance" id="toc-background-and-significance" class="nav-link active" data-scroll-target="#background-and-significance"><span class="toc-section-number">1</span>  Background and Significance</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="toc-section-number">2</span>  Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="toc-section-number">3</span>  Results</a></li>
  <li><a href="#discussionconclusions" id="toc-discussionconclusions" class="nav-link" data-scroll-target="#discussionconclusions"><span class="toc-section-number">4</span>  Discussion/Conclusions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="toc-section-number">5</span>  References:</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="toc-section-number">6</span>  Appendix</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="background-and-significance" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Background and Significance</h1>
<p>In the late 1950s and early 1960s a phenomenon called white flight occurred where whites left multiracial areas in significant numbers. This left inner cities gutted of wealth, and contributed to the segregation between metro areas.</p>
<p>The Homeowners Loan Corporation (HOLC) was established in 1933 by FDR as part of the new deal. Its primary goal was to refinance home mortgages in default to prevent foreclosure. In order to categorize homes, HOLC created a map to rank neighborhoods, ranged A through D. A(green) was the best rating, B(blue) was still desirable, C(yellow) was declining, D(red) was hazardous. While certain economic criteria were included, the A rating was reserved for communities that were “ethnically homogeneous”, and the D rating was reserved for communities that were “infiltrated” by “undesirable populations”. Banks refused to lend to individuals in areas with the lower grades, making it impossible for blacks and other racial minorities to receive mortgages. We’re interested to determine whether this discrimination is still prevalent today, after almost 87 years. Are there lasting effects from HOLC grades in the 1930s with racial diversity in 2020, and can we find the relationship between HOLC grades with today’s demographics?</p>
</section>
<section id="methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methods</h1>
<p>a.&nbsp;<em>Data collection</em>.</p>
<p>We retrieved the redlining data sets from github. The data come from 2020 population estimates of race and ethnicity in areas specified in HOLC maps from 1935-1940, originally found in the Mapping Inequality Project. Population estimates include surrounding regions of every statistical area’s HOLC map for each ethnicity group and grade. Race and ethnicity data are from the 2020 U.S decennial census, and separated into the 5 following groups: White, Black, Asian, Latino/Hispanic, and Other. Each observation self identified themselves to be part of either of the 5 groups.</p>
<p>Each racial and ethnic group has a location quotient (LQ) that is a measure of segregation. LQs compare each group’s presence in small areas to its overall presence in surrounding areas. Presence is measured as an ethnic group’s proportion of the total population. LQ values above one indicate that an ethnic group is over represented in the HOLC zone in question, whereas scores below one suggest a group is underrepresented.</p>
<p>b.&nbsp;<em>Variable creation</em>.</p>
<p>We created a race indicator variable titled “Race_Indicator” which is a non ordinal categorical variable with two levels, “black” and “not black”. The variable labels counties according to their plurality population. Counties with a majority black population receive the label “black”, and counties with a different racial majority are labeled “not black”.</p>
<p>We also created a different race indicator variable titled “Race” which is a non ordinal categorical variable with five levels, “Black”, “White”, “Asian”, “Hispanic”, and “Other”. Each county is labeled according to one of the five aforementioned categories depending on its plurality population.</p>
<p>Finally, we created a dummy variable called HOLC_Indicator, which classifies a good holc rating (A, B) as 1, and a bad HOLC rating (C, D) as 0.</p>
<p>c.&nbsp;<em>Analytic Methods</em>.</p>
<p>We will first create a logistic regression model, to determine the effect of various explanatory variables on the HOLC rating. We will start by selecting various possible explanatory variables, including holc_grade, pct_white, pct_black, surr_area_pct_white, and surr_area_pct white. Next, we create a dummy variable to help us classify the HOLC grades. A and B HOLC grades, which we consider good, will be represented by a 1 in the dummy variable. C and D HOLC grades, which we consider bad, will be represented by a 0 in the dummy variable. Next, we split the data with the validation split method. We use a 70/30 split with not testing and testing data because we do not have many data points, and so we require more data points for testing than is typical. The not testing data will be further split 75/25 to training and validation. The final percentages are: 52.5% training, 17.5% validation, and 30% testing.</p>
<p>Next, we will create many possible models by combining the explanatory variables and their interactions, to test our data with. We will select the model with the highest accuracy. If more than one model is equally accurate, we will choose the simpler model. Next, we will run the model with the testing data, and collect predictions, estimates and variable importance. Finally, we will create a graphing data set by combining the explanatory variables from the testing split with probability predictions and predictions. We will create a 2d color coded scatter plot which displays one explanatory variable per axis and graphs the exponential component of the logistic regression function as a linear line. We will also create a 3d plot displaying both explanatory variables and calculated probability. Finally, we will display a variable importance bar graph as well as statistics for the model.</p>
<p>Then we’ll further examine our results by conducting a permutation test to determine whether HOLC grades are assigned independent of race, more specifically, whether their assignment is independent of being black. There are 4 possible HOLC grades ranging from A to D, A being the best and D being the worst . We will designate counties according to their plurality population. counties with a larger percentage of blacks will be labeled “black”, for black state, those with a different racial majority will be labeled “not black”. We are testing to see whether HOLC rating is independent of being in a black state or not. We will use the infer package to generate 1,000 permutations, with sample size 551, and create the permutation distribution. The test statistic is a chi-squared value from the data. From there we will calculate the p-value and compare it to our significance level of <span class="math inline">\(\alpha\)</span> = 0.001.</p>
<p>We will then try to confirm our results by conducting another test for independence using another chi-squared method, though instead we’ll perform it without simulating data . There are 2 categories, HOLC rating and majority race. The first, as mentioned previously, is an ordinal categorical variable with 4 levels. Majority race is a non-ordinal categorical variable denoted by “black” and “not black”. In total there will be 8 cells, providing us with a Chi-Squared distribution of 6 degrees of freedom. Then we would use Base R commands to find the test statistic and p-value. Finally, we would compare the p-value to our significance level of <span class="math inline">\(\alpha\)</span> = 0.001</p>
<p>Lastly, we try to expand our hypothesis testing to examine whether the racial discrimination in HOLC grade assignment extends to race in general, as opposed to just black labeled counties. To do so, we conduct another simulated permutation test using a chi-squared statistic. Again, we designate counties to one of the five levels “Black”, “White”, “Asian”, “Hispanic”, and “Other” according to their racial plurality. We are testing to determine whether HOLC rating is independent of a county’s racial assignment. We will use the infer package to generate 1,000 permutations, with sample size 551, and create the permutation distribution of chi-squared statistics under the null hypothesis that the variables are independent. From there we will calculate the p-value and compare it to our significance level of <span class="math inline">\(\alpha\)</span> = 0.001.</p>
</section>
<section id="results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results</h1>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-1_c1001476497daf265b18b79a0c81a31c">

</div>
<p><strong>Statistical Summaries</strong></p>
<p><em>Graph 1. is a breakdown of HOLC grade by percentage white.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-2_5e5620cc42d8287987189a97264374c3">
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Graph 2. is a breakdown of HOLC grade by percentage black.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-3_83fed69024a6238228b36e4f59bc5272">
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Graph 3. displays the racial breakdown of the dataset across the entire entire United States.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-4_7ddf1121ffcabec6f0d264eeae3d424c">
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  type   white black  hisp asian other
  &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 min     3.77  0.31   1.1  0.09  0.88
2 median 59.0  13.4    8.8  2.01  5.55
3 max    94.1  85.4   93.9 31.4  17.7 
4 sd     22.5  18.7   16.9  3.67  2.07</code></pre>
</div>
</div>
<p><strong>Data creation for Logistic Regression</strong></p>
<p><em>A sample of the final data pre-split.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-5_ee71d31e9936700ce9be94be98746877">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  holc_grade pct_white pct_black surr_area_pct_black surr_area_pct_white HOLC_…¹
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;               &lt;dbl&gt;               &lt;dbl&gt; &lt;fct&gt;  
1 A               66.8      23.3                16.6                71.2 1      
2 B               61.2      24.3                16.6                71.2 1      
3 C               64.9      20.3                16.6                71.2 0      
4 D               40.8      45.7                16.6                71.2 0      
5 A               72.9       7.8                11.8                66.8 1      
# … with abbreviated variable name ¹​HOLC_Indicator</code></pre>
</div>
</div>
<p><strong>Testing models on validation data</strong></p>
<p><em>Model selection based off of various explanatory varaibles. Model 1 is the null model and we selected Model 5 with Percentage white and surrounding area percentage white was selected as it had the highest accuracy. We have also displayed the correct ratio of</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-6_d51f05d6cec4d1b92b887cf0d8bc5d23">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  model_name accuracy roc_auc
       &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1          1    0.660   0.698
2          2    0.711   0.808
3          3    0.711   0.814
4          4    0.701   0.760
5          5    0.763   0.858
6          6    0.742   0.855
7          7    0.670   0.687
8          8    0.691   0.794</code></pre>
</div>
</div>
<p><strong>Using Model</strong></p>
<p><em>The model’s accuracy on testing data is 0.765. We have also displayed a sample of the models predicted values, and estimates. 39 out of 166 total predictions were incorrect, and we display that the dominant variable is pct_white in Graph 4.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-7_940b8b3433b66ebf0cedfa8b8bac7723">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  .metric  .estimator .estimate .config             
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               
1 accuracy binary         0.765 Preprocessor1_Model1
2 roc_auc  binary         0.911 Preprocessor1_Model1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  id               .pred_0 .pred_1  .row .pred_class HOLC_Indicator .config     
  &lt;chr&gt;              &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt; &lt;fct&gt;       &lt;fct&gt;          &lt;chr&gt;       
1 train/test split   0.717  0.283      7 0           0              Preprocesso…
2 train/test split   0.969  0.0306     8 0           0              Preprocesso…
3 train/test split   0.585  0.415     12 0           0              Preprocesso…
4 train/test split   0.261  0.739     13 1           1              Preprocesso…
5 train/test split   0.353  0.647     15 1           0              Preprocesso…</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                estimate std.error statistic  p.value
  &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)          -1.11      0.447      -2.48 1.33e- 2
2 pct_white             0.114     0.0118      9.63 5.72e-22
3 surr_area_pct_white  -0.0930    0.0130     -7.15 8.88e-13</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction  0  1
         0 59 15
         1 24 68</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  stats::glm(formula = ..y ~ ., family = stats::binomial, data = data)

Coefficients:
        (Intercept)            pct_white  surr_area_pct_white  
           -1.10778              0.11403             -0.09299  

Degrees of Freedom: 384 Total (i.e. Null);  382 Residual
Null Deviance:      533.7 
Residual Deviance: 346.4    AIC: 352.4</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Data Visualization</strong></p>
<p><em>Graph 5. graphs the exponent of the logit model as a linear function, and the accuracy of the model with Percentage white on the x axis, and surrounding percentage white on the y axis. Points above the linear line are predicted to have a bad holc rating, and points below are predicted to have a good holc rating. The actual holc rating is represented by red and blue, with red being a bad rating, and blue being a good rating. We can see that the model is accurate at making strong predictions but struggles when it is a tough choice between a good and bad rating.</em></p>
<p><em>Graph 6. is a 3d model with pct_white on the x axis, surrounding percentage white on the y axis, and the predicted value on the z axis. Similarly to graph 4, blue represents a good HOLC grade, and green represents a bad HOLC grade.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-8_41cccc89a7b150ca7464d94daaa721fa">
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<div id="htmlwidget-f843a680a1fcd62a0dd1" style="width:100%;height:464px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-f843a680a1fcd62a0dd1">{"x":{"visdat":{"bf8e5ca86440":["function () ","plotlyVisDat"]},"cur_data":"bf8e5ca86440","attrs":{"bf8e5ca86440":{"x":{},"y":{},"z":{},"color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20]}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Graph 6. Predicted Holc Value by %White of area and Surrounding Area","scene":{"xaxis":{"title":"pct_white"},"yaxis":{"title":"surr_area_pct_white"},"zaxis":{"title":"prediction_value"}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[56.02,33.86,55.87,87.56,86.14,74.37,23.78,28.75,10.24,59.18,36.32,33.94,40.45,31.05,22.84,55.1,33.31,24.29,48.36,24.5,60.32,60.05,41.52,47.84,57.32,78.61,84.29,77.55,76.38,57.49,39.33,6.6,22.79,49.98,10.55,37.54,63.9,10.81,67.06,60.45,56,78.49,22.04,49.22,28.27,73.98,70.27,37.86,33.41,67.62,29.93,28.41,41.41,45.18,41.5,83.12,30.39,44.15,33.69,25.08,41.47,33.69,47.23,8.38,43.51,20.39,48.48,16.1,9.78,50.81,75.8,66.11,49.66,79.38,73.34,38.28,55.67,33.65,56.07,21.13,6.63,48.43,40.27],"y":[66.75,66.75,60.27,88.92,88.92,74.48,45.3,37.57,40.39,73.93,53.54,65.38,58.26,48.74,63.89,60.77,36.48,36.48,55.88,36.91,66.97,57.95,59.81,57.81,63.41,83.89,85.92,77.53,77.53,57.22,62.76,40.21,52.14,48.98,18.26,60,67.52,44.95,66.89,64.77,64.77,74.67,25.21,54.41,22.92,69.16,69.16,52.06,34.81,56.88,43.2,35.35,59.23,59.05,35.32,89.11,43.14,58.55,41.48,41.44,55.6,53.72,42.08,14.36,40.9,28.91,55.35,31.46,31.46,64.25,77.66,68.03,68.03,78.08,78.08,49.46,53.61,53.61,58.39,40.43,40.43,47.2,74.84],"z":[0.28347522177392,0.0306465401889324,0.415372283101222,0.647359750539937,0.609577473581457,0.609749802404748,0.0685740182101846,0.210276442225566,0.0242184344507942,0.225368257692479,0.125080657969479,0.0349727351003299,0.128625186985928,0.10912338152975,0.0116041569510612,0.383174285017091,0.33138261394636,0.150529389483846,0.312190214306769,0.148489661778457,0.387594807812099,0.586756377500313,0.126165110078971,0.263342227595432,0.384981099612449,0.513664507562795,0.625641989957743,0.628371462098129,0.596722192376119,0.531595300169387,0.078757804615073,0.0163918796415341,0.0336420259372679,0.509116914120113,0.167583587267312,0.0826561596462432,0.474929628929777,0.0170371360990191,0.578969029439892,0.440772732656767,0.321814989986168,0.710616510258664,0.281104893984645,0.364673178794181,0.496087308986641,0.710231980924783,0.616205590140298,0.16356429887499,0.369296017368738,0.78805700609856,0.152871174461751,0.239470388643093,0.130799616410994,0.19041904951757,0.58414387154362,0.520865042772676,0.160538667194647,0.179720785588846,0.245349444212422,0.108939707364618,0.17515813202148,0.0943364203183985,0.590141026042302,0.184279762334857,0.512522893091827,0.18675976629589,0.325868681871815,0.0999745761746303,0.0512634602604316,0.21604187713423,0.577764160188123,0.526027980102923,0.145352721313367,0.664354150582746,0.498510081005525,0.207136722527788,0.563339216898866,0.0948218038921207,0.46402010628252,0.0788483253142555,0.0161194309711371,0.506314123484346,0.0300170951457935],"type":"scatter3d","mode":"markers","name":"0","marker":{"color":"rgba(102,194,165,1)","line":{"color":"rgba(102,194,165,1)"}},"textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"line":{"color":"rgba(102,194,165,1)"},"frame":null},{"x":[91.38,68.41,54.45,90.13,58.09,70.27,31.85,50.77,55.61,77.29,61.32,67.76,43.56,83.68,56.34,85.4,79.95,84.34,72.27,82.46,60.46,85.23,84.95,69.43,26.13,63.47,71.6,79.02,18.26,71.96,42.12,91.25,81.49,61.63,73.87,47.71,61.89,77.09,55.71,85.23,78.78,53.14,40.33,28.57,82.35,49.18,88.9,88.78,72.72,70.65,38.76,72.37,67.28,77.6,85.39,44.2,57.95,75.85,66.38,64.25,76.91,73.48,66.89,49.85,37.67,79.22,70.09,60.93,52.4,80.55,81.84,82.76,77.28,77.79,81.2,47.66,48.36,59.14,70.82,75.43,88.72,88.48,61.56],"y":[88.92,42.21,42.21,74.48,48.99,62.77,37.57,53.54,65.38,68.28,58.26,48.74,48.74,68.41,63.89,60.77,55.88,66.97,57.95,57.81,63.41,85.92,73.54,57.22,13.35,62.76,40.21,72.96,18.26,67.52,44.95,66.89,66.89,64.77,42.94,42.94,54.41,53.74,22.92,74.86,27.89,27.89,14.37,14.37,59.04,34.81,57.89,56.88,56.88,43.2,36.59,59.23,35.32,67.9,89.11,43.14,41.48,41.44,42.08,46.07,61.17,40.9,40.9,28.91,35.17,55.35,55.35,60.39,60.39,64.25,76.98,55.53,68.03,78.08,78.08,49.46,14.55,60,63.72,64.64,87.46,35.6,74.84],"z":[0.739434990728712,0.940896059521359,0.764178961884025,0.904072265408992,0.723180777200873,0.744158564399196,0.27492464132294,0.4261702650149,0.300138374090178,0.795071564502297,0.614568762897811,0.889552322546547,0.337767586694349,0.888182576112513,0.348681263405947,0.951611672532393,0.943330961638058,0.907331273539098,0.851191010609899,0.94877380266802,0.47242391806101,0.650389192516805,0.850696118457993,0.815781365070686,0.652551096962123,0.572791058004037,0.965016340487286,0.753586239307378,0.326576921245292,0.693957306166274,0.381068748712272,0.9559271298,0.876958848219742,0.474154158908489,0.965183732589978,0.584022264911017,0.708802343708568,0.936140384651721,0.957435137122227,0.838789444389441,0.994941636272252,0.913568667404762,0.896097100037917,0.692885349735932,0.942241744543707,0.779534491615609,0.974563608695111,0.976478739828361,0.86930036709859,0.949352542670821,0.477334413124821,0.837037005741709,0.963715461070013,0.806348616100187,0.584760822388634,0.480129659888305,0.837902701366593,0.975576780809406,0.92744918903192,0.873717379205419,0.877999259381845,0.969747837130197,0.937966256517107,0.868528411261807,0.479270975966799,0.941488350574253,0.850328080234659,0.555770365764948,0.321119839458834,0.891122350834207,0.743750714129311,0.959501553552661,0.798650172936766,0.622801685539823,0.708949299733655,0.432242991496665,0.954932702286042,0.514039737974994,0.739248782412954,0.814900955786656,0.70588746667424,0.99656645535734,0.259629948374438],"type":"scatter3d","mode":"markers","name":"1","marker":{"color":"rgba(141,160,203,1)","line":{"color":"rgba(141,160,203,1)"}},"textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"line":{"color":"rgba(141,160,203,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><strong>Permutation Test - Simulated Chi-Squared</strong></p>
<p>We begin our hypothesis testing with a Permutation Test using a chi-squared statistic.</p>
<p>Our Hypothesis:</p>
<p><span class="math inline">\(\ H_0\)</span>: The HOLC grade assigned to a particular county is independent of whether the plurality of the population in that county is black or not black.</p>
<p><span class="math inline">\(\ H_1\)</span>: The HOLC grade assigned to a particular county is not independent of whether the plurality of the population in that county is black or not black.</p>
<p>We are using a significance level of <span class="math inline">\(\alpha = 0.001\)</span> . Because we are conducting three hypothesis tests in total. We divide <span class="math inline">\(\alpha\)</span> by 3 to avoid any unintentional p-hacking. Therefore our new significance level will be <span class="math inline">\(\alpha_2 = 0.00033\)</span> .</p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-9_9fbc1de8ff0f8428640cc1443b254341">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Race_Indicator grade
  &lt;fct&gt;          &lt;fct&gt;
1 Not Black      A    
2 Not Black      B    
3 Not Black      C    
4 Black          D    
5 Not Black      A    </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: grade (factor)
Explanatory: Race_Indicator (factor)
# A tibble: 1 × 1
   stat
  &lt;dbl&gt;
1  65.1</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<p>We find a chi-squared statistic of 65.09, which means that our observed statistic is located far into the right tail of the permutation simulated chi-squared distribution with 6 degrees of freedom. This observed statistic has a p-value of essentially 0 and is less than the significance level of 0.00033. Therefore we reject the null hypothesis and conclude that the assignment of a HOLC rating to a county is not independent of whether its ethnic plurality is black or not.</p>
<p><strong>Base R - Chi Squared Test</strong></p>
<p>We’ll now try to confirm our previous result from the permutation test by using a traditional chi-squared test method. The hypotheses remain the same:</p>
<p><span class="math inline">\(\ H_0\)</span>: The HOLC grade assigned to a particular county is independent of whether the plurality of the population in that county is black or not black.</p>
<p><span class="math inline">\(\ H_1\)</span>: The HOLC grade assigned to a particular county is not independent of whether the plurality of the population in that county is black or not black.</p>
<p>Significance level: <span class="math inline">\(\alpha_2 = 0.00033\)</span></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-10_c2386593723a0bb245ac451e64567bc4">
<div class="cell-output cell-output-stdout">
<pre><code>            A   B   C  D
Black       4   8  23 47
Not Black 134 130 114 91</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>X-squared 
 65.08896 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>df 
 3 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.800981e-14</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            A   B   C  D
Black       4   8  23 47
Not Black 134 130 114 91</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  A         B         C         D
Black      20.53721  20.53721  20.38838  20.53721
Not Black 117.46279 117.46279 116.61162 117.46279</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  A         B          C         D
Black     -3.649148 -2.766496  0.5783860  5.839357
Not Black  1.525850  1.156779 -0.2418457 -2.441662</code></pre>
</div>
</div>
<p>It appears that the traditional chi-squared test confirms the results from the previous permutation test. The chi-squared statistic is also 65.09, and the estimated p-value of 4.14e-12 is far smaller than our significance level of 0.00033. Therefore we reject the null hypothesis and conclude that the assignment of a HOLC rating to a county is not independent of whether its ethnic plurality is black or not.</p>
<p><strong>Second Permutation Test - Simulated Chi-Squared Test for Independence</strong></p>
<p>In this test we expand our investigation to determine whether levels of discrimination extends race as a whole, as opposed to just black and white.</p>
<p><span class="math inline">\(\ H_0\)</span>: The HOLC grade assigned to a particular county is independent of race in general.</p>
<p><span class="math inline">\(\ H_1\)</span>: The HOLC grade assigned to a particular county is not independent of race in general.</p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-11_e3570a291d13845b0962afbf525ebb01">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  grade Race 
  &lt;fct&gt; &lt;chr&gt;
1 A     White
2 B     White
3 C     White
4 D     Black
5 A     White</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: grade (factor)
Explanatory: Race (factor)
# A tibble: 1 × 1
   stat
  &lt;dbl&gt;
1  91.4</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<p>We find a chi-squared statistic of 91.42, which means that our observed statistic is located far into the right tail of the permutation simulated chi-squared distribution. This observed statistic has a p-value of essentially 0 and is less than the significance level of 0.00033. Therefore we reject the null hypothesis and conclude that the assignment of a HOLC rating to a county is not independent of race in general.</p>
</section>
<section id="discussionconclusions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Discussion/Conclusions</h1>
<p>The objective was to determine whether or not statistical areas are still segregated from their HOLC grade in the early 20th century. Our findings showed that there is both a significance in HOLC ratings and that a lower HOLC rating can be explained by a lower percentage black population in and around the MSA and the location quotient. We also found that a better HOLC rating was correlated with a more white population in and around the county. The linear probability model showed that as racial diversity increased, the probability that the HOLC rating was good decreased. This is in line with previous research that shows a lack of independence between HOLC ratings and racial diversity.</p>
<p>The first simulated chi-squared permutation test for independence between a county being assigned its HOLC grade and its plurality population being black yielded a significant result with a p-value of approximately zero, and a chi-squared statistic of 65.1. Although we cannot conclude that a county’s plural race being black or not is causal of HOLC grade, we can certainly say that their association is not due to random chance. Though given the historical background of HOLC ratings and its supposed discriminatory methods, it would be feasible to think that discrimination is still potentially prevalent. Discrepancy in HOLC ratings is best demonstrated by the residual table below, which shows that blacks in class A are underrepresented by over three standard deviations.</p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-12_e57975219f22fff58803d91928e2db4b">
<div class="cell-output cell-output-stdout">
<pre><code>                  A         B          C         D
Black     -3.649148 -2.766496  0.5783860  5.839357
Not Black  1.525850  1.156779 -0.2418457 -2.441662</code></pre>
</div>
</div>
<p>Our second hypothesis test is an extension of the first, except we test for independence between HOLC grade and plurality population in general. This test allowed us to examine whether ratings were based on race more generally as opposed to a binary opposition of black and non-black. This simulated chi-squared permutation test resulted in a p-value of approximately zero, and a chi-squared statistic even more significant than the one from the previous test at 91.42. Though like in the previous test, we cannot conclude that a county’s plural race is causal of HOLC rating, rather we can only say that their association is not due to random chance.</p>
<p>The logistic regression describes the relationship between the HOLC Indicator and today’s racial breakdown per statistical area. After running many models with different predictors, we find the two best predictors are pct_white and surr_area_pct_white, with pct_white having slightly more importance than surr_area_pct_white.&nbsp;</p>
<p>We believe this model is fairly accurate, as it was 76.5% accurate in predicting the correct HOLC Indicator in the testing data. When training this model, it was only 76.2% accurate, but since the two accuracies are so close, it gives us confidence that the model is not overfitted, and will be similarly accurate for different groupings of data. Out of the 166 Indicators predicted in the testing data, 118 were correct and 39 were incorrect, with the majority of the incorrect predictions close to the decision boundary.</p>
<p>We found there is a positive correlation between pct_white and HOLC Indicator, and a negative correlation between surr_area_pct_white and the HOLC Indicator. The coefficient of pct_white was 0.114 which means an increase in 1% of the percentage white in the area increases the odds of the area receiving a good rating by 12.88%. However, an increase in 1% of the surrounding areas percentage white decreases the odds of the area receiving a good rating by 8.88%. This could be describing the white flight phenomenon. When whites left cities in the 1900s to move to the surrounding areas, those areas became more diverse and the surrounding areas became more white. Thus, there is a possible correlation between the diversity of the surrounding area and the diversity of the area itself. When surrounding areas are whiter, the areas in the center is more diverse and receives a lower HOLC rating. We were unable to test for the correlation between pct_white and surr_area_pct_white, because this dataset was not randomly selection, which is a limitation.&nbsp;</p>
<p>Due to the historical context in which HOLC grades exist, and their well-known racial discrimination, we can infer that our hypothesis testing and regression results confirm that this discrimination is most likely still present. The implications of such prejudicial methods span from micro to macro levels. On a micro level, people/families who are unable to receive mortgage loans due to their race will find it difficult to grow their personal property wealth and overall wealth for their future, which could mean that families ultimately miss out on potentially higher levels of prosperity. If this discrimination occurs on a large scale, like our second hypothesis test suggests, it could hinder the economic growth of communities with black or Latino racial pluralities. Over time, the slow growth, or lack thereof, will contribute to widening socioeconomic disparities between minority and majority ethnicities not just within counties, or states, but across the United States as a whole.</p>
<p>One thing to note is that we decided to group grades together to conduct our regressions. We grouped A and B into good, and C and D into Bad, which could have caused some problems with respect to information loss. But we remain confident in the strength of our findings.</p>
<p>In the future it would be interesting to conduct a time-series analysis and determine racial diversity over time. We also do not know the percentages of HOLC grades. This dataset selects one A, B, C, and D per state which is not representative of the correct distribution. In future research it would be beneficial to have a dataset with randomly selected counties, and separate the dataset further.</p>
<p><span class="citation" data-cites="tidyverse">[<a href="#ref-tidyverse" role="doc-biblioref">1</a>]</span>, <span class="citation" data-cites="tidymodels">[<a href="#ref-tidymodels" role="doc-biblioref">2</a>]</span>, <span class="citation" data-cites="vip">[<a href="#ref-vip" role="doc-biblioref">3</a>]</span>, <span class="citation" data-cites="plotly">[<a href="#ref-plotly" role="doc-biblioref">4</a>]</span>, <span class="citation" data-cites="USCLAP">[<a href="#ref-USCLAP" role="doc-biblioref">5</a>]</span>, <span class="citation" data-cites="Redlining">[<a href="#ref-Redlining" role="doc-biblioref">6</a>]</span>, <span class="citation" data-cites="HOLC">[<a href="#ref-HOLC" role="doc-biblioref">7</a>]</span>, <span class="citation" data-cites="ggfortify">[<a href="#ref-ggfortify" role="doc-biblioref">8</a>]</span>, <span class="citation" data-cites="infer">[<a href="#ref-infer" role="doc-biblioref">9</a>]</span>, <span class="citation" data-cites="skimr">[<a href="#ref-skimr" role="doc-biblioref">10</a>]</span></p>
</section>
<section id="references" class="level1" data-number="5">


</section>
<section id="appendix" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Appendix</h1>
<p>Numerical and Visual Summaries</p>
<p><em>Location Quotients are small-area measures of segregation that specifically compare one racial/ethnic group’s proportion in a granular geography to their proportion in a larger surrounding geography. An LQ above 1 for a given racial group indicates overrepresentation in that HOLC zone relative to the broader surrounding area, and values below 1 indicate underrepresentation.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-13_e08334d5bf5146e7c57e235c81ad57e3">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>whitelq <span class="ot">&lt;-</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lq_white)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>white_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(whitelq, percentage)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> whitelq <span class="sc">%&gt;%</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>blacklq <span class="ot">&lt;-</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lq_black)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>black_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(blacklq, percentage)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> blacklq <span class="sc">%&gt;%</span> </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>hisplq <span class="ot">&lt;-</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lq_hisp)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>hisp_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(hisplq, percentage)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> hisplq <span class="sc">%&gt;%</span> </span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>asianlq <span class="ot">&lt;-</span></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lq_asian)</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>asian_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(asianlq, percentage)</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> asianlq <span class="sc">%&gt;%</span> </span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>otherlq <span class="ot">&lt;-</span></span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lq_other)</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>other_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(otherlq, percentage)</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>o <span class="ot">&lt;-</span> otherlq <span class="sc">%&gt;%</span> </span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(white_l,black_l,hisp_l,asian_l,other_l)</span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>new2 <span class="sc">%&gt;%</span> </span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> percentage, <span class="at">y =</span> value))<span class="sc">+</span></span>
<span id="cb23-46"><a href="#cb23-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> percentage))<span class="sc">+</span></span>
<span id="cb23-47"><a href="#cb23-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Breakdown of Location Quotients in the United Counties - Amrit, Dean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>xlabels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"min"</span>, <span class="st">"median"</span>, <span class="st">"max"</span>, <span class="st">"sd"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ylabels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"type"</span>, <span class="st">"white LQ"</span>, <span class="st">"black LQ"</span>, <span class="st">"hisp LQ"</span>, <span class="st">"asian LQ"</span>, <span class="st">"other lQ"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>data3 <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(xlabels, <span class="fu">t</span>(w),<span class="fu">t</span>(b),<span class="fu">t</span>(h),<span class="fu">t</span>(a),<span class="fu">t</span>(o))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data3) <span class="ot">&lt;-</span> ylabels</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>data3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  type   `white LQ` `black LQ` `hisp LQ` `asian LQ` `other lQ`
  &lt;chr&gt;       &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1 min         0.16       0.02      0.18       0.11       0.39 
2 median      0.98       1.02      1          0.74       1.05 
3 max         4.11       6.64      3.64       2.68       2.2  
4 sd          0.477      0.652     0.469      0.425      0.201</code></pre>
</div>
</div>
<p><em>This graph compares a metro’s areas white percentage compared to the surrounding areas white percentage.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-14_c5516d4b6b7e753bc0b5f3f926aaf19f">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> surr_area_pct_white, <span class="at">y =</span> pct_white))<span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()<span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Statistical Area's percentage white compared to surrounding areas - Amrit, Dean"</span>) <span class="sc">+</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Percentage of Whites in Surrounding Area'</span>)<span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Percentage White'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>The following graph compares the Statistical Areas percentage white compared to the surrounding areas percentage white.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-15_c399927fa963f9dad99cad9e63ec1e24">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> surr_area_pct_black, <span class="at">y =</span> pct_black))<span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()<span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Statistical Area's percentage white compared to surrounding areas - Amrit, Dean"</span>) <span class="sc">+</span> </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Percentage of Whites in Surrounding Area'</span>)<span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Percentage White'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MATH-254-Project---Amrit-_-Dean-Final_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>CODE FOR ANALYSIS SECTION</strong></p>
<p>loading libraries and data</p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-16_f69efafd3dd75a2c6125634506a80fb3">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>remote <span class="ot">&lt;-</span> <span class="st">'https://raw.githubusercontent.com/'</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>account <span class="ot">&lt;-</span><span class="st">'fivethirtyeight/'</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>folder <span class="ot">&lt;-</span> <span class="st">'data/master/redlining/'</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>file <span class="ot">&lt;-</span> <span class="st">'metro-grades.csv'</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="fu">str_c</span>(remote, account, folder, file)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">#head(data, 10)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Regression</strong></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-17_1fc03a453d6000b7c2fa7f09ee322312">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>white <span class="ot">&lt;-</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(pct_white)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>white_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(white, percentage)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>median_w <span class="ot">&lt;-</span> white <span class="sc">%&gt;%</span> </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>black <span class="ot">&lt;-</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(pct_black)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>black_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(black, percentage)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>median_b <span class="ot">&lt;-</span> black <span class="sc">%&gt;%</span> </span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>hisp <span class="ot">&lt;-</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(pct_hisp)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>hisp_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(hisp, percentage)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>median_h <span class="ot">&lt;-</span> hisp <span class="sc">%&gt;%</span> </span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>asian <span class="ot">&lt;-</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(pct_asian)</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>asian_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(asian, percentage)</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>median_a <span class="ot">&lt;-</span> asian <span class="sc">%&gt;%</span> </span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>other <span class="ot">&lt;-</span></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(pct_other)</span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>other_l <span class="ot">&lt;-</span> <span class="fu">gather</span>(other, percentage)</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a>median_o <span class="ot">&lt;-</span> other <span class="sc">%&gt;%</span> </span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>(min, median, max, sd))</span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(white_l,black_l,hisp_l,asian_l,other_l)</span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a>new <span class="sc">%&gt;%</span> </span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> percentage, <span class="at">y =</span> value))<span class="sc">+</span></span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> percentage))<span class="sc">+</span></span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Graph 3. Racial breakdown and summary of the Entire United States - Amrit, Dean"</span>)</span>
<span id="cb29-47"><a href="#cb29-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-48"><a href="#cb29-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-49"><a href="#cb29-49" aria-hidden="true" tabindex="-1"></a>xlabels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"min"</span>, <span class="st">"median"</span>, <span class="st">"max"</span>, <span class="st">"sd"</span>)</span>
<span id="cb29-50"><a href="#cb29-50" aria-hidden="true" tabindex="-1"></a>ylabels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"type"</span>, <span class="st">"white"</span>, <span class="st">"black"</span>, <span class="st">"hisp"</span>, <span class="st">"asian"</span>, <span class="st">"other"</span>)</span>
<span id="cb29-51"><a href="#cb29-51" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(xlabels, <span class="fu">t</span>(median_w),<span class="fu">t</span>(median_b),<span class="fu">t</span>(median_h),<span class="fu">t</span>(median_a),<span class="fu">t</span>(median_o))</span>
<span id="cb29-52"><a href="#cb29-52" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data2) <span class="ot">&lt;-</span> ylabels</span>
<span id="cb29-53"><a href="#cb29-53" aria-hidden="true" tabindex="-1"></a>data2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Data creation for Logistic Regression</strong></p>
<p><em>A sample of the final data pre-split.</em></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-18_cb5a0cfc3e715ad3c0d94619a4bb5601">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(holc_grade, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>         pct_white, </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>         pct_black, </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>         surr_area_pct_black, </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>         surr_area_pct_white) <span class="sc">%&gt;%</span> </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>()</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co">#df1</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  df1 <span class="sc">%&gt;%</span> </span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HOLC_Indicator =</span> <span class="fu">if_else</span>(holc_grade <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'A'</span>, <span class="st">'B'</span>), <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#select(-holc_grade) %&gt;% </span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HOLC_Indicator =</span> <span class="fu">factor</span>(HOLC_Indicator))</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&gt;%</span> </span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>df_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(<span class="at">data =</span> df2, <span class="at">prop =</span> .<span class="dv">7</span>, <span class="at">strata =</span> HOLC_Indicator)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="co">#df_split</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>df_training <span class="ot">&lt;-</span> <span class="fu">training</span>(df_split)</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>df_testing <span class="ot">&lt;-</span> <span class="fu">testing</span>(df_split)</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a><span class="co">#df_training</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a><span class="co">#df_testing</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>df_validation_resample <span class="ot">&lt;-</span> <span class="fu">validation_split</span>(<span class="at">data =</span> df_training, <span class="at">prop =</span> <span class="fl">0.75</span>, <span class="at">strata =</span> HOLC_Indicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Testing models on validation data</strong></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-19_a8b1bdb0c6e311e872bbc92422f2b365">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>model_1_specs <span class="ot">&lt;-</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">'glm'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">'classification'</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                  pct_black, df_validation_resample)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>                  pct_black <span class="sc">+</span> </span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>                  surr_area_pct_black, df_validation_resample)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>model_3 <span class="ot">&lt;-</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>                  pct_black <span class="sc">+</span> </span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>                  surr_area_pct_black <span class="sc">+</span> </span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>                  pct_black<span class="sc">*</span>surr_area_pct_black, df_validation_resample)</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>model_4 <span class="ot">&lt;-</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>                  pct_white, df_validation_resample)</span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a>model_5 <span class="ot">&lt;-</span></span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a>                  pct_white <span class="sc">+</span> </span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a>                  surr_area_pct_white, df_validation_resample)</span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a>model_6 <span class="ot">&lt;-</span></span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a>                  pct_white <span class="sc">+</span> </span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a>                  surr_area_pct_white <span class="sc">+</span> </span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a>                  pct_white<span class="sc">*</span>surr_area_pct_white, df_validation_resample)</span>
<span id="cb31-42"><a href="#cb31-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-43"><a href="#cb31-43" aria-hidden="true" tabindex="-1"></a>model_7 <span class="ot">&lt;-</span></span>
<span id="cb31-44"><a href="#cb31-44" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-45"><a href="#cb31-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-46"><a href="#cb31-46" aria-hidden="true" tabindex="-1"></a>                  pct_black <span class="sc">+</span> </span>
<span id="cb31-47"><a href="#cb31-47" aria-hidden="true" tabindex="-1"></a>                  surr_area_pct_white <span class="sc">+</span> </span>
<span id="cb31-48"><a href="#cb31-48" aria-hidden="true" tabindex="-1"></a>                  pct_black<span class="sc">*</span>surr_area_pct_white, df_validation_resample)</span>
<span id="cb31-49"><a href="#cb31-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-50"><a href="#cb31-50" aria-hidden="true" tabindex="-1"></a>model_8 <span class="ot">&lt;-</span></span>
<span id="cb31-51"><a href="#cb31-51" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb31-52"><a href="#cb31-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb31-53"><a href="#cb31-53" aria-hidden="true" tabindex="-1"></a>                  pct_white <span class="sc">+</span> </span>
<span id="cb31-54"><a href="#cb31-54" aria-hidden="true" tabindex="-1"></a>                  surr_area_pct_black <span class="sc">+</span> </span>
<span id="cb31-55"><a href="#cb31-55" aria-hidden="true" tabindex="-1"></a>                  pct_white<span class="sc">*</span>surr_area_pct_black, df_validation_resample)</span>
<span id="cb31-56"><a href="#cb31-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-57"><a href="#cb31-57" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(model_1, model_2, model_3, model_4, model_5, model_6, model_7, model_8)</span>
<span id="cb31-58"><a href="#cb31-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-59"><a href="#cb31-59" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_1)</span></span>
<span id="cb31-60"><a href="#cb31-60" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_2)</span></span>
<span id="cb31-61"><a href="#cb31-61" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_3)</span></span>
<span id="cb31-62"><a href="#cb31-62" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_4)</span></span>
<span id="cb31-63"><a href="#cb31-63" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_5)</span></span>
<span id="cb31-64"><a href="#cb31-64" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_6)</span></span>
<span id="cb31-65"><a href="#cb31-65" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_7)</span></span>
<span id="cb31-66"><a href="#cb31-66" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_metrics(model_8)</span></span>
<span id="cb31-67"><a href="#cb31-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-68"><a href="#cb31-68" aria-hidden="true" tabindex="-1"></a><span class="co">#df_training %&gt;% </span></span>
<span id="cb31-69"><a href="#cb31-69" aria-hidden="true" tabindex="-1"></a><span class="co">#  count(HOLC_Indicator)</span></span>
<span id="cb31-70"><a href="#cb31-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-71"><a href="#cb31-71" aria-hidden="true" tabindex="-1"></a>validation_results <span class="ot">&lt;-</span> </span>
<span id="cb31-72"><a href="#cb31-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(models) <span class="sc">%&gt;%</span> </span>
<span id="cb31-73"><a href="#cb31-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model_name =</span> <span class="fu">row_number</span>())</span>
<span id="cb31-74"><a href="#cb31-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-75"><a href="#cb31-75" aria-hidden="true" tabindex="-1"></a>validation_results <span class="sc">%&gt;%</span> </span>
<span id="cb31-76"><a href="#cb31-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.metrics, model_name) <span class="sc">%&gt;%</span> </span>
<span id="cb31-77"><a href="#cb31-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(.metrics) <span class="sc">%&gt;%</span> </span>
<span id="cb31-78"><a href="#cb31-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.metric, .estimate, model_name) <span class="sc">%&gt;%</span> </span>
<span id="cb31-79"><a href="#cb31-79" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> .metric, <span class="at">values_from =</span> .estimate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Using Model</strong></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-20_8f836ddfe6f4972d9187fdcf66071340">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the model on testing data</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use model 5. There doesn't appear to be a large impact of interaction.</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>final_model <span class="ot">&lt;-</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  model_1_specs <span class="sc">%&gt;%</span> </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">last_fit</span>(HOLC_Indicator <span class="sc">~</span> </span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>             pct_white <span class="sc">+</span> surr_area_pct_white, df_split)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(final_model)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">collect_predictions</span>(final_model)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>predictions <span class="sc">%&gt;%</span> </span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> <span class="fu">tidy</span>(<span class="fu">extract_fit_engine</span>(final_model))</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>estimates </span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>predictions <span class="sc">%&gt;%</span> </span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">conf_mat</span>(HOLC_Indicator, .pred_class)</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_fit_engine</span>(final_model)</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="fu">vip</span>(<span class="fu">extract_fit_engine</span>(final_model))<span class="sc">+</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Graph 4. Variable importance plot for all explanatory variables"</span>)</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="co">#as_tibble(df_testing) %&gt;% </span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a><span class="co">#  select(pct_white, surr_area_pct_white)</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a><span class="co">#df_testing</span></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a><span class="co">#exp(0.11402624)</span></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a><span class="co">#1- exp(-0.09299)</span></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Data Visualization</strong></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-21_176e4da67be4fc3c7a62cf6133d61a4d">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>graph_data <span class="ot">&lt;-</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(predictions<span class="sc">$</span>.pred_1, </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>            predictions<span class="sc">$</span>HOLC_Indicator, </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>            df_testing) <span class="sc">%&gt;%</span> </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">prediction_value =</span> ...<span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">actual =</span> ...<span class="dv">2</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>graph_data <span class="sc">%&gt;%</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>pct_white, <span class="at">y =</span> surr_area_pct_white, <span class="at">color =</span> actual))<span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="fl">0.11403</span><span class="sc">/</span><span class="fl">0.09299</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">1.10778</span><span class="sc">/</span><span class="fl">0.09299</span>)<span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Graph 5. Predicted Value of HOLC rating by %White and %Surrounding White"</span>)<span class="sc">+</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percentage White(%)"</span>)<span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Surroudning Percentage White%"</span>)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">plot_ly</span>(graph_data, </span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">x =</span> <span class="sc">~</span>pct_white, </span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="sc">~</span>surr_area_pct_white, </span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">z =</span> <span class="sc">~</span> prediction_value, </span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="sc">~</span>actual) <span class="sc">%&gt;%</span> </span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layout</span>(<span class="at">title =</span> <span class="st">'Graph 6. Predicted Holc Value by %White of area and Surrounding Area'</span>)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>d</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a><span class="co">#var.test(prediction_value ~ pct_white, data = graph_data)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Permutation Test - Simulated Chi-Squared</strong></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-22_8c6ffb3fe19f1efc852693e89f59bcae">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(black_pop,white_pop,asian_pop,hisp_pop,other_pop) <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>()</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>permutation_df <span class="ot">&lt;-</span> </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  df2 <span class="sc">%&gt;%</span> </span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Race_Indicator =</span> <span class="fu">apply</span>(df2, <span class="at">MARGIN =</span> <span class="dv">1</span>, <span class="at">FUN =</span> which.max)) <span class="sc">%&gt;%</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Race_Indicator =</span> <span class="fu">if_else</span>(Race_Indicator<span class="sc">==</span><span class="dv">1</span>, <span class="st">'Black'</span>, <span class="st">'Not Black'</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Race_Indicator)  <span class="sc">%&gt;%</span> </span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">grade =</span> data<span class="sc">$</span>holc_grade) <span class="sc">%&gt;%</span> </span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grade =</span> <span class="fu">factor</span>(grade), <span class="at">Race_Indicator =</span> <span class="fu">factor</span>(Race_Indicator))</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>permutation_df <span class="sc">%&gt;%</span> </span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Conducting the Permutation Test#</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>obs_stat1 <span class="ot">&lt;-</span></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>  permutation_df <span class="sc">%&gt;%</span></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(grade <span class="sc">~</span> Race_Indicator) <span class="sc">%&gt;%</span> </span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">'chisq'</span>)</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>obs_stat1</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>permutation_dist <span class="ot">&lt;-</span></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>  permutation_df <span class="sc">%&gt;%</span> </span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(grade <span class="sc">~</span> Race_Indicator) <span class="sc">%&gt;%</span> </span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesise</span>(<span class="at">null =</span> <span class="st">'independence'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">'permute'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">'chisq'</span>)</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>permutation_dist <span class="sc">%&gt;%</span> </span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> obs_stat1, <span class="at">direction =</span> <span class="st">'right'</span>) <span class="sc">+</span> </span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Simulated Chi-Squared Permutation Distribution'</span>) <span class="sc">+</span></span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Chi-Squared Values'</span>)</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>permutation_dist <span class="sc">%&gt;%</span> </span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_p_value</span>(<span class="at">obs_stat =</span> obs_stat1, <span class="at">direction =</span> <span class="st">'right'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Base R - Chi Squared Test</strong></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-23_7fc47967500172add17ad35ea0617a5e">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>Chisq_tibble <span class="ot">&lt;-</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>permutation_df <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Race_Indicator, grade) <span class="sc">%&gt;%</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> grade, <span class="at">values_from =</span> n, <span class="at">id_cols =</span> Race_Indicator)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>chisq_matrix <span class="ot">&lt;-</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>(tibble<span class="sc">::</span><span class="fu">column_to_rownames</span>(Chisq_tibble, <span class="st">"Race_Indicator"</span>))</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>chisq_matrix</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>chisq_test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(chisq_matrix)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>chisq_test<span class="sc">$</span>statistic</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>chisq_test<span class="sc">$</span>parameter</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>chisq_test<span class="sc">$</span>p.value</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>chisq_test<span class="sc">$</span>observed</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>chisq_test<span class="sc">$</span>expected</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>chisq_test<span class="sc">$</span>residuals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Second Permutation Test - Simulated Chi-Squared Test for Independence</strong></p>
<div class="cell" data-hash="MATH-254-Project---Amrit-_-Dean-Final_cache/html/unnamed-chunk-24_6928e570a4b78e4054e5281a738fda4c">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>new_df <span class="ot">&lt;-</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Race_Indicator =</span> <span class="fu">apply</span>(df2, <span class="at">MARGIN =</span> <span class="dv">1</span>, <span class="at">FUN =</span> which.max)) <span class="sc">%&gt;%</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">race =</span> <span class="fu">case_when</span>(</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>      Race_Indicator <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Black"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>      Race_Indicator <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"White"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>      Race_Indicator <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Asian"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>      Race_Indicator <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Hispanic"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>      Race_Indicator <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Other"</span>))</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>twoperm_df <span class="ot">&lt;-</span> </span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>permutation_df <span class="sc">%&gt;%</span> </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Race_Indicator)  <span class="sc">%&gt;%</span> </span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">Race =</span> new_df<span class="sc">$</span>race)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>twoperm_df <span class="sc">%&gt;%</span> </span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>obs_stat2 <span class="ot">&lt;-</span></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>twoperm_df <span class="sc">%&gt;%</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(grade <span class="sc">~</span> Race) <span class="sc">%&gt;%</span> </span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">'chisq'</span>)</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>obs_stat2</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>permutation_dist <span class="ot">&lt;-</span></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>twoperm_df <span class="sc">%&gt;%</span> </span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(grade <span class="sc">~</span> Race) <span class="sc">%&gt;%</span> </span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesise</span>(<span class="at">null =</span> <span class="st">'independence'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">'permute'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">'chisq'</span>)</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a>permutation_dist <span class="sc">%&gt;%</span> </span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> obs_stat2, <span class="at">direction =</span> <span class="st">'right'</span>) <span class="sc">+</span> </span>
<span id="cb36-34"><a href="#cb36-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Simulated Chi-Squared Permutation Distribution'</span>) <span class="sc">+</span></span>
<span id="cb36-35"><a href="#cb36-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Chi-Squared Values'</span>)</span>
<span id="cb36-36"><a href="#cb36-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-37"><a href="#cb36-37" aria-hidden="true" tabindex="-1"></a>permutation_dist <span class="sc">%&gt;%</span> </span>
<span id="cb36-38"><a href="#cb36-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_p_value</span>(<span class="at">obs_stat =</span> obs_stat2, <span class="at">direction =</span> <span class="st">'right'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">5 References:</h2><div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-tidyverse" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline"><span class="smallcaps">Wickham</span>, H., <span class="smallcaps">Averick</span>, M., <span class="smallcaps">Bryan</span>, J., <span class="smallcaps">Chang</span>, W., <span class="smallcaps">McGowan</span>, L. D., <span class="smallcaps">François</span>, R., <span class="smallcaps">Grolemund</span>, G., <span class="smallcaps">Hayes</span>, A., <span class="smallcaps">Henry</span>, L., <span class="smallcaps">Hester</span>, J., <span class="smallcaps">Kuhn</span>, M., <span class="smallcaps">Pedersen</span>, T. L., <span class="smallcaps">Miller</span>, E., <span class="smallcaps">Bache</span>, S. M., <span class="smallcaps">Müller</span>, K., <span class="smallcaps">Ooms</span>, J., <span class="smallcaps">Robinson</span>, D., <span class="smallcaps">Seidel</span>, D. P., <span class="smallcaps">Spinu</span>, V., <span class="smallcaps">Takahashi</span>, K., <span class="smallcaps">Vaughan</span>, D., <span class="smallcaps">Wilke</span>, C., <span class="smallcaps">Woo</span>, K. and <span class="smallcaps">Yutani</span>, H. (2019). <a href="https://doi.org/10.21105/joss.01686">Welcome to the <span></span>tidyverse<span></span></a>. <strong>4</strong> 1686.</div>
</div>
<div id="ref-tidymodels" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline"><span class="smallcaps">Kuhn</span>, M. and <span class="smallcaps">Wickham</span>, H. (2020). <a href="https://www.tidymodels.org">Tidymodels: A collection of packages for modeling and machine learning using tidyverse principles.</a></div>
</div>
<div id="ref-vip" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline"><span class="smallcaps">Greenwell</span>, B. M. and <span class="smallcaps">Boehmke</span>, B. C. (2020). <a href="https://doi.org/10.32614/RJ-2020-013">Variable importance plots<span></span>an introduction to the vip package</a>. <strong>12</strong>.</div>
</div>
<div id="ref-plotly" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline"><span class="smallcaps">Sievert</span>, C. (2020). <a href="https://plotly-r.com">Interactive web-based data visualization with r, plotly, and shiny</a>.</div>
</div>
<div id="ref-USCLAP" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline"><span class="smallcaps">Carl Friedrich Gauss</span>, A. N. K. (2022). <a href="https://turalsadigov.github.io/MATH_254/Project%20Template,%20Instructions%20and%20Checkpoints/MATH-254-Project-Report-Template.html
">USCLAP project template</a>.</div>
</div>
<div id="ref-Redlining" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline"><span class="smallcaps">Project</span>, M. I. and <span class="smallcaps">Census</span>, 2020. U. (2022). <a href="https://github.com/fivethirtyeight/data/tree/master/redlining
">Lasting legacy of redlining</a>.</div>
</div>
<div id="ref-HOLC" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline"><span class="smallcaps">Lavery</span>, D. (2020). <a href="https://www.arcgis.com/home/item.html?id=063cdb28dd3a449b92bc04f904256f62
">Home owners’ loan corporation (HOLC) neighborhood redlining grade</a>.</div>
</div>
<div id="ref-ggfortify" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[8] </div><div class="csl-right-inline"><span class="smallcaps">Tang</span>, Y., <span class="smallcaps">Horikoshi</span>, M. and <span class="smallcaps">Li</span>, W. (2016). <a href="https://doi.org/10.32614/RJ-2016-060">Ggfortify: Unified interface to visualize statistical result of popular r packages</a>. <strong>8</strong>.</div>
</div>
<div id="ref-infer" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[9] </div><div class="csl-right-inline"><span class="smallcaps">Couch</span>, S. P., <span class="smallcaps">Bray</span>, A. P., <span class="smallcaps">Ismay</span>, C., <span class="smallcaps">Chasnovski</span>, E., <span class="smallcaps">Baumer</span>, B. S. and <span class="smallcaps">Çetinkaya-Rundel</span>, M. (2021). <a href="https://doi.org/10.21105/joss.03661"><span></span>Infer<span></span>: An <span></span>r<span></span> package for tidyverse-friendly statistical inference</a>. <strong>6</strong> 3661.</div>
</div>
<div id="ref-skimr" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[10] </div><div class="csl-right-inline"><span class="smallcaps">Waring</span>, E., <span class="smallcaps">Quinn</span>, M., <span class="smallcaps">McNamara</span>, A., <span class="smallcaps">Arino de la Rubia</span>, E., <span class="smallcaps">Zhu</span>, H. and <span class="smallcaps">Ellis</span>, S. (2022). <a href="https://CRAN.R-project.org/package=skimr">Skimr: Compact and flexible summaries of data</a>.</div>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>